permissions:
  contents: write

name: GitHub Readme Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare output directory
        run: mkdir -p profile

      - name: Generate stats card
        uses: cicirello/user-statistician@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_1 }}
        with:
          image-file: profile/stats.svg

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add profile/stats.svg
          git commit -m "chore: update stats" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
